package org.usfirst.frc199.Robot2016.commands;

import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 * Determines starting location and defense to cross from SmartDashboard.
 */
public class AutoMode extends CommandGroup {

	/**
	 * 
	 * @param defense
	 *            the defense which we are trying to pass 1 - low bar (X) 2 -
	 *            portcullis (A) 3 - cheval de frise (A) 4 - Moat (B) 5 -
	 *            Ramparts (B) 6 - Drawbridge (C) 7 - Sally Port (C) 8 - Rock
	 *            Wall (D) 9 - Rough Terrain (D)
	 * @param position
	 *            can be 1, 2, 3, 4, 5
	 * 
	 */
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
	public AutoMode(int defense, int position) {

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
		// Add Commands here:
		// e.g. addSequential(new Command1());
		// addSequential(new Command2());
		// these will run in order.

		addSequential(new AutoDrive(30));

		switch (defense) {
		case 2: // portcullis
			addSequential(new AutoDrive(20)); // 20 inches
			addSequential(new RaiseIntake());
			break;
		case 3: // cheval de frise
			addSequential(new AutoDrive(20)); // 20 inches
			addSequential(new LowerIntake());
			break;
		case 4: // moat
			addSequential(new AutoDrive(50)); // 50 inches
			break;
		case 5: // ramparts
			addSequential(new AutoDrive(50)); // 50 inches
			break;
		case 6: // drawbridge
			break;
		case 7: // sally port
			break;
		case 8: // rock wall
			addSequential(new AutoDrive(50)); // 50 inches
			break;
		case 9: // rough terrain
			addSequential(new AutoDrive(50)); // 50 inches
			break;
		default:
			System.out.println("Wrong Defense");
			break;
		}

		addSequential(new AutoDrive(60)); // 60 inches
		
		switch (position) {
		case 2:
			addSequential(new AutoTurn(-30)); // -40 degrees (towards the right)
			addSequential(new AutoAlignAngle()); // Of Course, assuming that the camera can see the target in its current position
			break;
		case 3:
			addSequential(new AutoAlignAngle()); // Of Course, assuming that the camera can see the target in its current position
			break;
		case 4:
			addSequential(new AutoAlignAngle()); // Of Course, assuming that the camera can see the target in its current position
			break;
		case 5:
			addSequential(new AutoTurn(10)); // 10 degrees (towards the left)
			addSequential(new AutoAlignAngle()); // Of Course, assuming that the camera can see the target in its current position
			break;
		default:
			System.out.println("Wrong position");
			break;
		}
		
		addSequential(new RunShooter());

		// To run multiple commands at the same time,
		// use addParallel()
		// e.g. addParallel(new Command1());
		// addSequential(new Command2());
		// Command1 and Command2 will run in parallel.

		// A command group will require all of the subsystems that each member
		// would require.
		// e.g. if Command1 requires chassis, and Command2 requires arm,
		// a CommandGroup containing them would require both the chassis and the
		// arm.
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS

	}
}
