// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc199.Robot2016.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc199.Robot2016.Robot;

/**
 *
 */
public class AutoDrive extends Command {

	private final double distance;
	private final double slide;
	private boolean gradualDrive;

	/**
	 * @param distance - The distance to travel in inches
	 */
	public AutoDrive(double distance) {
		this.distance = distance;
		this.slide = 0;
		gradualDrive = false;
        requires(Robot.drivetrain);
	}

	// Target distance and slide in inches, requires Drivetrain
	public AutoDrive(double distance, double slide) {
		this.distance = distance;
		this.slide = slide;
		requires(Robot.drivetrain);
		gradualDrive = false;
	}

	public AutoDrive(double distance, double slide, boolean gradualdrive) {
		this.distance = distance;
		this.slide = slide;
		requires(Robot.drivetrain);
		gradualDrive = gradualdrive;
	}

	// Called just before this Command runs the first time
	protected void initialize() {
		Robot.drivetrain.setAutoTarget(distance, 0);
	}

	// Called repeatedly when this Command is scheduled to run
	protected void execute() {
		Robot.drivetrain.updateAuto();
	}

	// Make this return true when this Command no longer needs to run execute()
	protected boolean isFinished() {
		return Robot.drivetrain.autoReachedTarget();
	}

	// Called once after isFinished returns true
	protected void end() {
		Robot.drivetrain.arcadeInput(0, 0);
	}

	// Called when another command which requires one or more of the same
	// subsystems is scheduled to run
	protected void interrupted() {
		end();
	}
}

