package org.usfirst.frc199.Robot2016.subsystems;

import org.usfirst.frc199.Robot2016.Robot;
import org.usfirst.frc199.Robot2016.RobotMap;

import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.command.Subsystem;

/**
 * Launches boulders into the high goal.
 */
public class Shooter extends Subsystem implements DashboardSubsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
	

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final SpeedController flywheelMotor = RobotMap.shooterFlywheelMotor;
    private final Encoder flywheelEncoder = RobotMap.shooterFlywheelEncoder;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void prepareToShootLow ( ){
    	
    }
    public void prepareToShootHigh () {
    	
    }
    public void raise (){
    	
    }
    public void lower (){
    	
    }
    public void triggerShooter (){
    	
    }
    

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    public void runShooter(double speed) {
    	flywheelMotor.set(speed);
    }
}